name: uiflutter
description: "Flutter module for holding UI of application."

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  permission_handler: ^11.0.0
  device_info_plus: ^12.3.0
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_light.png
    - assets/images/bg_dark.png
    - assets/images/main_image.svg
  generate: true
  module:
    androidX: true
    androidPackage: com.example.uiflutter
    iosBundleIdentifier: com.example.uiflutter
