name: uiflutter
description: "Flutter module for holding UI of application."

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  json_annotation: ^4.8.1
  permission_handler: ^11.0.0
  device_info_plus: ^12.3.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  logger: ^2.7.0
  fluttertoast: ^9.0.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg_light.png
    - assets/images/bg_dark.png
    - assets/images/placeholder_history_image.svg
    - assets/images/ic_external.svg
    - assets/images/ic_ion.svg
    - assets/images/ic_barometer.svg
    - assets/images/ic_turbidity.svg
    - assets/images/ic_respiratory_rate.svg
    - assets/images/ic_body_temp.svg
    - assets/images/ic_heart_pulse.svg
    - assets/images/ic_blood_pressure.svg
    - assets/images/ic_voltage.svg
    - assets/images/ic_magnetic_field.svg
    - assets/images/ic_current_strength.svg
    - assets/images/ic_pressure.svg
    - assets/images/ic_temp_high.svg
    - assets/images/ic_colors.svg
    - assets/images/ic_ph_probe.svg
    - assets/images/ic_ph.svg
    - assets/images/ic_temp_probe.svg
    - assets/images/ic_humidity.svg
    - assets/images/ic_illumination.svg
    - assets/images/ic_conductivity.svg
    - assets/images/ic_accelerometer.svg
    - assets/images/ic_ambient_temp_light.svg
    - assets/images/ic_ambient_temp_dark.svg
    - assets/images/ic_air_pressure.svg
    - assets/images/ic_gps.svg
    - assets/images/ic_shimmer.svg
  generate: true
  module:
    androidX: true
    androidPackage: com.example.uiflutter
    iosBundleIdentifier: com.example.uiflutter
